# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 753)
        MainWindow.setStyleSheet("/* ---------------- 全局基础样式 ---------------- */\n"
"* {\n"
"    /* 像素风字体（需将\"PixelMplus12-Regular.ttf\"放到项目目录，或替换为系统字体） */\n"
"    font-family: \"PixelMplus12\", \"微软雅黑\", \"SimHei\", sans-serif;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #0A0A1A; /* 暗黑赛博背景 */\n"
"    color: #FFFFFF; /* 默认文字白色 */\n"
"}\n"
"\n"
"/* ---------------- 窗口样式 ---------------- */\n"
"QMainWindow, QWidget#main_window {\n"
"    background-color: #0A0A1A;\n"
"    border: 2px solid #FF2E9F; /* 粉色霓虹边框 */\n"
"}\n"
"\n"
"/* 透明窗口适配（Live2D窗口） */\n"
"QWidget#live2d_window {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* ---------------- 按钮样式（核心） ---------------- */\n"
"QPushButton {\n"
"    /* 粉蓝渐变背景（Qt标准渐变写法） */\n"
"    background: transparent;\n"
"    color: #ffffff; /* 文字白色对比 */\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border-width: 2px; /* 必须设置边框宽度 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-color: #FF2E9F #00E5FF #00E5FF #FF2E9F;\n"
"    border-radius: 4px; /* 轻微圆角（像素风避免大圆角） */\n"
"    padding: 6px 12px; /* 按钮内边距（初始值） */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #696969; /*  hover背景 */\n"
"    padding-left: 9px;\n"
"    padding-top: 7px;\n"
"    /* 强化发光 */\n"
"    text-shadow: 0 0 8px #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"    background: #696969; \n"
"    border-color: #ffffff;\n"
"    padding-left: 10px;\n"
"    padding-top: 9px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #333344;\n"
"    color: #888888;\n"
"    border-color: #666666;\n"
"    text-shadow: none;\n"
"}\n"
"\n"
"/* ---------------- 文本浏览器（QTextBrowser） ---------------- */\n"
"QTextBrowser {\n"
"    background-color: #121228;\n"
"    color: #00E5FF; /* 霓虹蓝文字 */\n"
"    border: 1px solid #9D00FF; /* 紫色边框 */\n"
"    padding: 8px;\n"
"    /* 像素风文字 */\n"
"    font-size: 12px;\n"
"    /* 轻微文字发光 */\n"
"    text-shadow: 0 0 3px #00E5FF;\n"
"}\n"
"\n"
"/* ---------------- 标签（QLabel） ---------------- */\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* 标题标签 */\n"
"QLabel#title_label {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    /* Qt渐变文字写法（模拟，需结合透明背景） */\n"
"    color: #FF2E9F;\n"
"    text-shadow: 0 0 6px #FF2E9F, 0 0 10px #9D00FF;\n"
"}\n"
"\n"
"/* 普通文本标签 */\n"
"QLabel#normal_label {\n"
"    color: #FFD1DC; /* 浅粉色文字 */\n"
"    text-shadow: 0 0 2px #FF2E9F;\n"
"}\n"
"\n"
"/* ---------------- 分隔线（QFrame） ---------------- */\n"
"QFrame::HLine { /* Qt标准HLine选择器 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"                                     stop:0 #FF2E9F, stop:1 #00E5FF);\n"
"    height: 2px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* ---------------- 输入框（QLineEdit） ---------------- */\n"
"QLineEdit {\n"
"    background-color: #121228;\n"
"    color: #00E5FF;\n"
"    border: 2px solid #FF2E9F;\n"
"    padding: 6px;\n"
"    text-shadow: 0 0 3px #00E5FF;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #00E5FF;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* ---------------- 下拉框 ComboBox（带边框） ---------------- */\n"
"QComboBox {\n"
"    background-color: #333344; /* 控件底色 */\n"
"    border: 2px solid #333344; /* 合并边框属性（宽度+样式+颜色） */\n"
"    border-radius: 2px;\n"
"    padding: 4px;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* ComboBox 下拉列表 */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #121228;\n"
"    border: 2px solid #ff2e9f; /* 粉色列表边框 */\n"
"    selection-background-color: #ff2e9f; /* 选中项背景 */\n"
"    selection-color: #0a0a1a;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"/* ComboBox 下拉箭头 */\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/arrow_down.png); /* 可选：替换箭头图标，若无则用默认 */\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QFrame[frameShape=\"4\"] { /* HLine水平分隔线 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"                                     stop:0 #FF2E9F, stop:1 #00E5FF);\n"
"    height: 2px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* 全局Horizontal Slider轨道样式 */\n"
"QSlider::horizontal {\n"
"    /* 轨道高度（横线粗细） */\n"
"    height: 10px;\n"
"    /* 轨道背景：水平渐变（保持原渐变效果） */\n"
"    background: #696969;\n"
"    /* 轨道圆角，让横线更圆润 */\n"
"    border-radius: 1px;\n"
"    /* 内边距，避免滑块与轨道边缘重叠 */\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* 滑块样式（核心：黑色、圆形、适配轨道） */\n"
"QSlider::handle:horizontal {\n"
"    /* 滑块大小（宽高一致做成圆形） */\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    /* 滑块背景：纯黑色 */\n"
"    background: #000000;\n"
"    /* 圆形滑块（圆角设为宽高的一半） */\n"
"    border-radius: 8px;\n"
"    /* 滑块阴影（可选，增加立体感） */\n"
"    border: 1px solid #cccccc;\n"
"    /* 滑块居中（相对于轨道） */\n"
"    margin: -5px 0px -5px 0px;\n"
"}\n"
"\n"
"/* 滑块hover状态（可选，鼠标悬浮时加深） */\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #222222;\n"
"}\n"
"\n"
"/* 已拖动部分的轨道（可选，区分进度） */\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"                                     stop:0 #FF2E9F, stop:1 #00E5FF);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"/* ---------------- 标签页 TabWidget 样式 ---------------- */\n"
"QTabWidget {\n"
"    background-color: #0A0A1A; /* 匹配全局暗黑背景 */\n"
"    border-color: \n"
"   \n"
"}\n"
"\n"
"/* 标签栏整体（顶部显示） */\n"
"QTabWidget::tab-bar {\n"
"    alignment: left; /* 标签左对齐（可选：center 居中/right 右对齐） */\n"
"    margin-left: 4px; /* 标签栏左侧留白，像素风轻微偏移 */\n"
"}\n"
"\n"
"/* 单个标签（未选中状态） */\n"
"QTabBar::tab {\n"
"    background-color: #121228; /* 深色底色 */\n"
"    color: #FFFFFF; /* 浅粉色文字，匹配normal_label */\n"
"    border: 2px solid #FF2E9F; /* 粉色边框，匹配按钮初始边框 */\n"
"    border-bottom: none; /* 取消底部边框，避免与内容区重叠 */\n"
"    border-top-left-radius: 4px; /* 轻微圆角，像素风不做大圆角 */\n"
"    border-top-right-radius: 4px;\n"
"    padding: 6px 16px; /* 标签内边距，保证点击区域 */\n"
"    margin-right: 2px; /* 标签之间的间距 */\n"
"    font-weight: bold; /* 匹配全局粗体 */\n"
"    text-shadow: 0 0 2px #FF2E9F; /* 轻微霓虹发光 */\n"
"}\n"
"\n"
"/* 标签 hover 状态（鼠标悬浮） */\n"
"QTabBar::tab:hover {\n"
"    background-color: #333344; /* 匹配ComboBox底色 */\n"
"    color: #FFFFFF; /* 文字变白 */\n"
"    text-shadow: 0 0 8px #FFFFFF; /* 强化发光，匹配按钮hover */\n"
"}\n"
"\n"
"/* 标签选中状态（核心） */\n"
"QTabBar::tab:selected {\n"
"    background-color: #0A0A1A; /* 匹配窗口背景，视觉融合 */\n"
"    color: #00E5FF; /* 霓虹蓝文字，匹配TextBrowser */\n"
"    border-color: #00E5FF; /* 切换为蓝色边框，突出选中态 */\n"
"    border-bottom: 2px solid #0A0A1A; /* 覆盖内容区边框，避免双重线 */\n"
"    text-shadow: 0 0 6px #00E5FF; /* 蓝色霓虹发光 */\n"
"}\n"
"\n"
"\n"
"\n"
"/* TabWidget 内容区（标签对应的页面） */\n"
"QTabWidget::pane {\n"
"    background-color: #0A0A1A; /* 匹配全局背景 */\n"
"    border: 1px solid #000000; /* 粉色边框，匹配窗口边框 */\n"
"    top: -2px; /* 上移2px，与选中标签的底部无缝衔接 */\n"
"    padding: 8px; /* 内容区内边距，避免内容贴边 */\n"
"}\n"
"\n"
"/* 隐藏标签页右侧的滚动按钮（可选，像素风简化界面） */\n"
"QTabBar::scroll-button {\n"
"    width: 0;\n"
"    height: 0;\n"
"    border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.motions = QtWidgets.QComboBox(self.tab)
        self.motions.setObjectName("motions")
        self.horizontalLayout.addWidget(self.motions)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.auto_motion = QtWidgets.QRadioButton(self.tab)
        self.auto_motion.setEnabled(False)
        self.auto_motion.setObjectName("auto_motion")
        self.horizontalLayout_3.addWidget(self.auto_motion)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.time_interval = QtWidgets.QDoubleSpinBox(self.tab)
        self.time_interval.setEnabled(True)
        self.time_interval.setObjectName("time_interval")
        self.horizontalLayout_3.addWidget(self.time_interval)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.volume = QtWidgets.QSlider(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volume.sizePolicy().hasHeightForWidth())
        self.volume.setSizePolicy(sizePolicy)
        self.volume.setOrientation(QtCore.Qt.Horizontal)
        self.volume.setObjectName("volume")
        self.horizontalLayout_4.addWidget(self.volume)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_4.setStretch(0, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.set_param = QtWidgets.QPushButton(self.tab)
        self.set_param.setEnabled(True)
        self.set_param.setObjectName("set_param")
        self.horizontalLayout_2.addWidget(self.set_param)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.response_body = QtWidgets.QDoubleSpinBox(self.tab)
        self.response_body.setObjectName("response_body")
        self.gridLayout.addWidget(self.response_body, 2, 1, 1, 1)
        self.response_x = QtWidgets.QDoubleSpinBox(self.tab)
        self.response_x.setObjectName("response_x")
        self.gridLayout.addWidget(self.response_x, 0, 1, 1, 1)
        self.Reverse_Y = QtWidgets.QPushButton(self.tab)
        self.Reverse_Y.setEnabled(True)
        self.Reverse_Y.setObjectName("Reverse_Y")
        self.gridLayout.addWidget(self.Reverse_Y, 1, 2, 1, 1)
        self.reverse_body = QtWidgets.QPushButton(self.tab)
        self.reverse_body.setEnabled(True)
        self.reverse_body.setObjectName("reverse_body")
        self.gridLayout.addWidget(self.reverse_body, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.response_y = QtWidgets.QDoubleSpinBox(self.tab)
        self.response_y.setObjectName("response_y")
        self.gridLayout.addWidget(self.response_y, 1, 1, 1, 1)
        self.Reverse_X = QtWidgets.QPushButton(self.tab)
        self.Reverse_X.setEnabled(True)
        self.Reverse_X.setObjectName("Reverse_X")
        self.gridLayout.addWidget(self.Reverse_X, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.horizontalLayout_8.setStretch(0, 2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.scroll = QtWidgets.QScrollArea(self.tab)
        self.scroll.setWidgetResizable(True)
        self.scroll.setObjectName("scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 507, 328))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.main_vlayout = QtWidgets.QVBoxLayout()
        self.main_vlayout.setObjectName("main_vlayout")
        self.verticalLayout_8.addLayout(self.main_vlayout)
        self.scroll.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scroll)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.add = QtWidgets.QPushButton(self.tab)
        self.add.setObjectName("add")
        self.horizontalLayout_9.addWidget(self.add)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_conversation = QtWidgets.QWidget()
        self.tab_conversation.setObjectName("tab_conversation")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_conversation)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.tab_conversation)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.language = QtWidgets.QComboBox(self.tab_conversation)
        self.language.setObjectName("language")
        self.language.addItem("")
        self.language.addItem("")
        self.language.addItem("")
        self.horizontalLayout_6.addWidget(self.language)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.tab_conversation)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.voice = QtWidgets.QComboBox(self.tab_conversation)
        self.voice.setObjectName("voice")
        self.horizontalLayout_6.addWidget(self.voice)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_9 = QtWidgets.QLabel(self.tab_conversation)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.response_mouth = QtWidgets.QSpinBox(self.tab_conversation)
        self.response_mouth.setObjectName("response_mouth")
        self.horizontalLayout_6.addWidget(self.response_mouth)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.line_3 = QtWidgets.QFrame(self.tab_conversation)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.history = QtWidgets.QTextBrowser(self.tab_conversation)
        self.history.setEnabled(True)
        self.history.setStyleSheet("")
        self.history.setObjectName("history")
        self.verticalLayout_5.addWidget(self.history)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.message = QtWidgets.QLineEdit(self.tab_conversation)
        self.message.setText("")
        self.message.setObjectName("message")
        self.horizontalLayout_7.addWidget(self.message)
        self.send = QtWidgets.QPushButton(self.tab_conversation)
        self.send.setObjectName("send")
        self.horizontalLayout_7.addWidget(self.send)
        self.horizontalLayout_7.setStretch(0, 5)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_conversation, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Controller"))
        self.label.setText(_translate("MainWindow", "Motions"))
        self.auto_motion.setText(_translate("MainWindow", "Auto"))
        self.label_4.setText(_translate("MainWindow", "Time (min)"))
        self.label_6.setText(_translate("MainWindow", "   Volume"))
        self.set_param.setText(_translate("MainWindow", "Set tracking parameters"))
        self.Reverse_Y.setText(_translate("MainWindow", "Reverse Y"))
        self.reverse_body.setText(_translate("MainWindow", "Reverse Body"))
        self.label_5.setText(_translate("MainWindow", "Body Response"))
        self.label_3.setText(_translate("MainWindow", "Y Response"))
        self.label_2.setText(_translate("MainWindow", "X Response"))
        self.Reverse_X.setText(_translate("MainWindow", "Reverse X"))
        self.label_10.setText(_translate("MainWindow", "Parameter Control (Parameter, Response, Position)"))
        self.add.setText(_translate("MainWindow", "Add "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Motion"))
        self.label_7.setText(_translate("MainWindow", "言語："))
        self.language.setItemText(0, _translate("MainWindow", "日本語"))
        self.language.setItemText(1, _translate("MainWindow", "中文"))
        self.language.setItemText(2, _translate("MainWindow", "English"))
        self.label_8.setText(_translate("MainWindow", "ボイス："))
        self.label_9.setText(_translate("MainWindow", "口の開き幅"))
        self.history.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PixelMplus12\',\'微软雅黑\',\'SimHei\',\'sans-serif\'; font-size:12px; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.send.setText(_translate("MainWindow", "送信する"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_conversation), _translate("MainWindow", "Conversation"))
