# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(229, 398)
        Form.setStyleSheet("\n"
"/* ---------------- 全局基础样式 ---------------- */\n"
"* {\n"
"    /* 像素风字体（需将\"PixelMplus12-Regular.ttf\"放到项目目录，或替换为系统字体） */\n"
"    font-family: \"PixelMplus12\", \"微软雅黑\", \"SimHei\", sans-serif;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #0A0A1A; /* 暗黑赛博背景 */\n"
"    color: #FFFFFF; /* 默认文字白色 */\n"
"}\n"
"\n"
"/* ---------------- 窗口样式 ---------------- */\n"
"QMainWindow, QWidget#main_window {\n"
"    background-color: #0A0A1A;\n"
"    border: 2px solid #FF2E9F; /* 粉色霓虹边框 */\n"
"}\n"
"\n"
"/* 透明窗口适配（Live2D窗口） */\n"
"QWidget#live2d_window {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* ---------------- 按钮样式（核心） ---------------- */\n"
"QPushButton {\n"
"    /* 粉蓝渐变背景 */\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #FF2E9F, stop:1 #00E5FF);\n"
"    color: #0A0A1A; /* 文字深色对比 */\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #FFFFFF; /* 白色像素边框 */\n"
"    border-radius: 4px; /* 轻微圆角（像素风避免大圆角） */\n"
"    padding: 8px 16px;\n"
"    /* 霓虹发光效果 */\n"
"    text-shadow: 0 0 5px #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* 悬停时加深渐变 */\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #FF55B8, stop:1 #2DE2FF);\n"
"    /* 故障偏移效果 */\n"
"    padding-left: 9px;\n"
"    padding-top: 7px;\n"
"    /* 强化发光 */\n"
"    text-shadow: 0 0 8px #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* 按下时反向渐变 */\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"                                stop:0 #00E5FF, stop:1 #FF2E9F);\n"
"    /* 按压偏移 */\n"
"    padding-left: 10px;\n"
"    padding-top: 9px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #333344;\n"
"    color: #888888;\n"
"    border-color: #666666;\n"
"    text-shadow: none;\n"
"}\n"
"\n"
"/* ---------------- 文本浏览器（QTextBrowser） ---------------- */\n"
"QTextBrowser {\n"
"    background-color: #121228;\n"
"    color: #00E5FF; /* 霓虹蓝文字 */\n"
"    border: 1px solid #9D00FF; /* 紫色边框 */\n"
"    padding: 8px;\n"
"    /* 像素风文字 */\n"
"    font-size: 12px;\n"
"    /* 轻微文字发光 */\n"
"    text-shadow: 0 0 3px #00E5FF;\n"
"}\n"
"\n"
"/* ---------------- 标签（QLabel） ---------------- */\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* 标题标签 */\n"
"QLabel#title_label {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    /* 粉紫渐变文字 */\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"                                stop:0 #FF2E9F, stop:1 #9D00FF);\n"
"    -webkit-background-clip: text;\n"
"    color: transparent;\n"
"    text-shadow: 0 0 6px #FF2E9F;\n"
"}\n"
"\n"
"/* 普通文本标签 */\n"
"QLabel#normal_label {\n"
"    color: #FFD1DC; /* 浅粉色文字 */\n"
"    text-shadow: 0 0 2px #FF2E9F;\n"
"}\n"
"\n"
"/* ---------------- 分隔线（QFrame） ---------------- */\n"
"QFrame[frameShape=\"4\"] { /* HLine水平分隔线 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"                                     stop:0 #FF2E9F, stop:1 #00E5FF);\n"
"    height: 2px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* ---------------- 输入框（QLineEdit） ---------------- */\n"
"QLineEdit {\n"
"    background-color: #121228;\n"
"    color: #00E5FF;\n"
"    border: 2px solid #FF2E9F;\n"
"    padding: 6px;\n"
"    text-shadow: 0 0 3px #00E5FF;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #00E5FF;\n"
"    outline: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* ---------------- 下拉框 ComboBox（带边框） ---------------- */\n"
"QComboBox {\n"
"    background-color: #333344; /* 控件底色 */\n"
"    border-color: #333344；\n"
"    border-radius: 2px;\n"
"\n"
"}\n"
"/* ComboBox 下拉列表 */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #121228;\n"
"    border: 2px solid #ff2e9f; /* 粉色列表边框 */\n"
"    selection-background-color: #ff2e9f; /* 选中项背景 */\n"
"    selection-color: #0a0a1a;\n"
"}\n"
"/* ---------------- 全局基础样式 ---------------- */\n"
"* {\n"
"    /* 像素风字体（需将\"PixelMplus12-Regular.ttf\"放到项目目录，或替换为系统字体） */\n"
"    font-family: \"PixelMplus12\", \"微软雅黑\", \"SimHei\", sans-serif;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #0A0A1A; /* 暗黑赛博背景 */\n"
"    color: #FFFFFF; /* 默认文字白色 */\n"
"}\n"
"\n"
"/* ---------------- 窗口样式 ---------------- */\n"
"QMainWindow, QWidget#main_window {\n"
"    background-color: #0A0A1A;\n"
"    border: 2px solid #FF2E9F; /* 粉色霓虹边框 */\n"
"}\n"
"\n"
"/* 透明窗口适配（Live2D窗口） */\n"
"QWidget#live2d_window {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* ---------------- 按钮样式（核心） ---------------- */\n"
"QPushButton {\n"
"    /* 粉蓝渐变背景（Qt标准渐变写法） */\n"
"    background: transparent;\n"
"    color: #ffffff; /* 文字白色对比 */\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border-width: 2px; /* 必须设置边框宽度 */\n"
"    border-style: solid; /* 边框样式 */\n"
"    border-color: #FF2E9F #00E5FF #00E5FF #FF2E9F;\n"
"    border-radius: 4px; /* 轻微圆角（像素风避免大圆角） */\n"
"    padding: 6px 12px; /* 按钮内边距（初始值） */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #696969; /*  hover背景 */\n"
"    padding-left: 9px;\n"
"    padding-top: 7px;\n"
"    /* 强化发光 */\n"
"    text-shadow: 0 0 8px #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"    background: #696969; \n"
"    border-color: #ffffff;\n"
"    padding-left: 10px;\n"
"    padding-top: 9px;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #333344;\n"
"    color: #888888;\n"
"    border-color: #666666;\n"
"    text-shadow: none;\n"
"}\n"
"\n"
"/* ---------------- 文本浏览器（QTextBrowser） ---------------- */\n"
"QTextBrowser {\n"
"    background-color: #121228;\n"
"    color: #00E5FF; /* 霓虹蓝文字 */\n"
"    border: 1px solid #9D00FF; /* 紫色边框 */\n"
"    padding: 8px;\n"
"    /* 像素风文字 */\n"
"    font-size: 12px;\n"
"    /* 轻微文字发光 */\n"
"    text-shadow: 0 0 3px #00E5FF;\n"
"}\n"
"\n"
"/* ---------------- 标签（QLabel） ---------------- */\n"
"QLabel {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* 标题标签 */\n"
"QLabel#title_label {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    /* Qt渐变文字写法（模拟，需结合透明背景） */\n"
"    color: #FF2E9F;\n"
"    text-shadow: 0 0 6px #FF2E9F, 0 0 10px #9D00FF;\n"
"}\n"
"\n"
"/* 普通文本标签 */\n"
"QLabel#normal_label {\n"
"    color: #FFD1DC; /* 浅粉色文字 */\n"
"    text-shadow: 0 0 2px #FF2E9F;\n"
"}\n"
"\n"
"/* ---------------- 分隔线（QFrame） ---------------- */\n"
"QFrame::HLine { /* Qt标准HLine选择器 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"                                     stop:0 #FF2E9F, stop:1 #00E5FF);\n"
"    height: 2px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* ---------------- 输入框（QLineEdit） ---------------- */\n"
"QLineEdit {\n"
"    background-color: #121228;\n"
"    color: #00E5FF;\n"
"    border: 2px solid #FF2E9F;\n"
"    padding: 6px;\n"
"    text-shadow: 0 0 3px #00E5FF;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #00E5FF;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* ---------------- 下拉框 ComboBox（带边框） ---------------- */\n"
"QComboBox {\n"
"    background-color: #333344; /* 控件底色 */\n"
"    border: 2px solid #333344; /* 合并边框属性（宽度+样式+颜色） */\n"
"    border-radius: 2px;\n"
"    padding: 4px;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"/* ComboBox 下拉列表 */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #121228;\n"
"    border: 2px solid #ff2e9f; /* 粉色列表边框 */\n"
"    selection-background-color: #ff2e9f; /* 选中项背景 */\n"
"    selection-color: #0a0a1a;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"/* ComboBox 下拉箭头 */\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/arrow_down.png); /* 可选：替换箭头图标，若无则用默认 */\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QFrame[frameShape=\"4\"] { /* HLine水平分隔线 */\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, \n"
"                                     stop:0 #FF2E9F, stop:1 #00E5FF);\n"
"    height: 2px;\n"
"    border: none;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.head_x = QtWidgets.QComboBox(Form)
        self.head_x.setObjectName("head_x")
        self.horizontalLayout.addWidget(self.head_x)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.head_y = QtWidgets.QComboBox(Form)
        self.head_y.setObjectName("head_y")
        self.horizontalLayout_4.addWidget(self.head_y)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.head_z = QtWidgets.QComboBox(Form)
        self.head_z.setObjectName("head_z")
        self.horizontalLayout_8.addWidget(self.head_z)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.eye_x = QtWidgets.QComboBox(Form)
        self.eye_x.setObjectName("eye_x")
        self.horizontalLayout_2.addWidget(self.eye_x)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.eye_y = QtWidgets.QComboBox(Form)
        self.eye_y.setObjectName("eye_y")
        self.horizontalLayout_3.addWidget(self.eye_y)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.body_x = QtWidgets.QComboBox(Form)
        self.body_x.setObjectName("body_x")
        self.horizontalLayout_7.addWidget(self.body_x)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.body_z = QtWidgets.QComboBox(Form)
        self.body_z.setObjectName("body_z")
        self.horizontalLayout_9.addWidget(self.body_z)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.mouth = QtWidgets.QComboBox(Form)
        self.mouth.setObjectName("mouth")
        self.horizontalLayout_10.addWidget(self.mouth)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.prompt = QtWidgets.QTextEdit(Form)
        self.prompt.setObjectName("prompt")
        self.verticalLayout_2.addWidget(self.prompt)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ok = QtWidgets.QPushButton(Form)
        self.ok.setObjectName("ok")
        self.horizontalLayout_5.addWidget(self.ok)
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_5.addWidget(self.cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 4)
        self.verticalLayout_2.setStretch(6, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Parameter Settings"))
        self.label.setText(_translate("Form", "Head X"))
        self.label_4.setText(_translate("Form", "Head Y"))
        self.label_7.setText(_translate("Form", "Head Z"))
        self.label_2.setText(_translate("Form", "Eye X"))
        self.label_3.setText(_translate("Form", "Eye Y"))
        self.label_6.setText(_translate("Form", "Body X"))
        self.label_8.setText(_translate("Form", "Body Z"))
        self.label_9.setText(_translate("Form", "Mouth"))
        self.label_10.setText(_translate("Form", "Prompt"))
        self.ok.setText(_translate("Form", "OK"))
        self.cancel.setText(_translate("Form", "Cancel"))
